window.JUPAS_DATA = {
  checked: '2026-10-03',
  sources: [
    {id:'cds',title:'HKU CDS · 本科入口与 2027 调整',type:'本科官方',period:'2027–28',url:'https://www.cds.hku.hk/prospective-students/undergraduate/',note:'AppliedAI 自 2027–28 并入 6999；专业核心与入学入口须分别看待。'},
    {id:'reg',title:'HKU · 2026–27 CDS 学位规例目录',type:'本科官方',period:'2026–27',url:'https://www4.hku.hk/pubunit/drcd/undergraduate-2026-2027/1140-computingdatascience',note:'用于校验学位覆盖范围；并非 2027–28 的最终课程表。'},
    {id:'cs',title:'HKU · 6999 CS / AI & Data Science',type:'本科官方',period:'滚动更新页面',url:'https://www.cds.hku.hk/prospective-students/undergraduate/6999-computing-and-data-science/',note:'页面存在旧目录重定向；2027 入口以 CDS 总页公告为准。CS 起薪调查为 2023 年，不能当作 2027 起薪。'},
    {id:'delta',title:'HKU · 6200 Delta+',type:'本科官方',period:'当前官方页面',url:'https://www.cds.hku.hk/prospective-students/undergraduate/6200-computing-and-data-science-delta/',note:'两个 BEng 选项；香港 2.5 年 + 上海 1.5 年，含六个月合作实习；不接受内部转入。'},
    {id:'applied',title:'HKU · Applied AI 专业说明',type:'本科官方',period:'2026–27 及以前入口',url:'https://www.cds.hku.hk/prospective-students/undergraduate/6224-bachelor-of-arts-sciences-in-applied-artificial-intelligence/',note:'五个 concentration 的说明延续为方向参考；2027 具体学分应待当届规例确认。'},
    {id:'fintech',title:'HKU · BASc Financial Technology',type:'本科官方',period:'当前官方页面',url:'https://www.cds.hku.hk/prospective-students/undergraduate/6248-bachelor-of-arts-and-sciences-in-financial-technology/',note:'CDS 与商学院合办，结合计算、金融及政策监管。'},
    {id:'act',title:'HKU · BSc Actuarial Science',type:'本科官方',period:'当前官方页面',url:'https://www.cds.hku.hk/prospective-students/undergraduate/6729-bachelor-of-science-in-actuarial-science/',note:'IFoA / SOA 的豁免有成绩和课程条件；本科毕业不等于取得精算师资格。'},
    {id:'stat',title:'HKU · BStat 三个专业核心',type:'本科官方',period:'当前官方页面',url:'https://www.cds.hku.hk/prospective-students/undergraduate/6779-statistical-decision-sciences/',note:'DA、RM、ST 是 Professional Cores；可无配额转换，完成的专业核心记录在成绩单。'},
    {id:'arts',title:'HKU Arts · BA & BEng AI & Data Science',type:'本科官方',period:'当前官方页面',url:'https://arts.hku.hk/admissions/undergraduate-admissions/bachelor-of-arts-and-bachelor-of-engineering-in-artificial-intelligence-and-data-science-js6298/',note:'跨院五年双学位；补入 CDS 相关全学位范围。'},
    {id:'ibgm',title:'HKU Business · IBGM 课程结构',type:'本科官方',period:'当前页面；按入学年复核',url:'https://ug.hkubs.hku.hk/admission/degree-programmes',note:'IBGM 要求第二专业和海外交换；不是 HKUST GBUS。'},
    {id:'qfin',title:'HKU Business · BSc QFin',type:'本科官方',period:'当前官方页面',url:'https://ug.hkubs.hku.hk/programme/degree-programmes/bsc-qfin/introduction',note:'金融、数学、统计、编程结合；并不承诺量化交易职位。'},
    {id:'second',title:'HKU Business · 第二专业与选课限制',type:'本科官方',period:'当前官方页面',url:'https://ug.hkubs.hku.hk/programme/major-and-minor-options',note:'QFin 第二专业有甄选；成功声明专业不保证课程名额，且须满足先修与时间表。'},
    {id:'pg',title:'HKU CDS · 授课硕士目录',type:'硕博官方',period:'当前目录',url:'https://master.cds.hku.hk/',note:'列出 CS、ECIC、FTDA、MDASC、MStat。'},
    {id:'msccs',title:'HKU · MSc Computer Science',type:'硕博官方',period:'2026–27 页面',url:'https://master.cds.hku.hk/msccs/',note:'含安全、金融计算等方向；最终以申请年份正式资料为准。'},
    {id:'mdasc',title:'HKU · Master of Data Science 入学要求',type:'硕博官方',period:'当前要求页面',url:'https://mdasc.cds.hku.hk/admissions/',note:'数学、编程、初级统计各须有至少一门大学或专上课程；满足要求不保证录取。'},
    {id:'mstat',title:'HKU · Master of Statistics 入学要求',type:'硕博官方',period:'当前要求页面',url:'https://mstat.cds.hku.hk/admissions/',note:'要求矩阵与微积分、初级统计及线性建模基础。'},
    {id:'mscai',title:'HKU Science · MSc Artificial Intelligence',type:'硕博官方',period:'2027–28 硕士入学',url:'https://www.scifac.hku.hk/prospective/tpg/ArtificialIntelligence',note:'数学系主办、CDS 合办；当前全日制 1.5 年、学费 HK$420,000，仅作已公布年度参考。'},
    {id:'mfin',title:'HKU Business · Master of Finance',type:'硕博官方',period:'当前官方页面',url:'https://masters.hkubs.hku.hk/our-programmes/master-of-finance/',note:'金融进阶例子；不与 MFFinTech 或 CDS FTDA 混同。'},
    {id:'mfft',title:'HKU Business · Master of Finance in Financial Technology',type:'硕博官方',period:'当前官方页面',url:'https://masters.hkubs.hku.hk/our-programmes/master-of-finance-in-financial-technology/',note:'商学院、CDS、法律学院合办；不同于 MSc FTDA。'},
    {id:'mgm',title:'HKU Business · Master of Global Management',type:'硕博官方',period:'当前官方页面',url:'https://masters.hkubs.hku.hk/our-programmes/master-of-global-management/',note:'全球管理训练；IBGM 后是否值得读同类硕士应看新增技能和就业资源。'},
    {id:'mba',title:'HKU · 全日制 MBA 入学 FAQ',type:'硕博官方',period:'当前要求页面',url:'https://mba.hkubs.hku.hk/full-time-mba-faqs/',note:'至少两年毕业后全职工作经验；不作为本科直接升学默认路径。'},
    {id:'rpg',title:'HKU CDS · MPhil / PhD',type:'硕博官方',period:'当前官方页面',url:'https://www.cds.hku.hk/prospective-students/postgraduate/',note:'计算机科学、统计与精算研究路径；有 MPhil 与三年／四年 PhD。'},
    {id:'businessphd',title:'HKU Business · PhD 研究领域',type:'硕博官方',period:'当前官方页面',url:'https://phd.hkubs.hku.hk/programmes/fields-of-study',note:'包括 Finance、Management and Strategy、Innovation and Information Management 等领域。'},
    {id:'phdadmit',title:'HKU Business · PhD 要求与资助',type:'硕博官方',period:'2027–28；PGS 费率自 2025-09',url:'https://phd.hkubs.hku.hk/admissions/admission-application-and-tuition-fee',note:'一等本科或荣誉本科加硕士；须 GMAT/GRE、研究计划及推荐；非研究硕士背景通常为四年轨道。PGS 基本 HK$19,135/月。'},
    {id:'hkpfs',title:'RGC · Hong Kong PhD Fellowship',type:'资助官方',period:'2027–28 call circular',url:'https://www.ugc.edu.hk/eng/rgc/funding_opport/hkpfs/call_letter.html',note:'竞争性奖项：HK$344,400/年，三年；旅行研究补助另计。第四年资助须查大学安排。'},
    {id:'oxstat',title:'Oxford · MSc Statistical Science',type:'海外硕博官方',period:'2027–28',url:'https://www.ox.ac.uk/admissions/graduate/courses/msc-statistical-science',note:'要求一等或等同学位及高阶数学统计背景；不能仅凭专业名称判定。'},
    {id:'oxfinance',title:'Oxford · MSc Mathematical and Computational Finance',type:'海外硕博官方',period:'当前官方页面',url:'https://www.ox.ac.uk/admissions/graduate/courses/msc-mathematical-and-computational-finance',note:'以随机计算、数值方法和金融计算为重点；核对当届学术要求。'},
    {id:'berkeley',title:'Berkeley Haas · MFE Requirements',type:'海外硕博官方',period:'当前官方页面',url:'https://mfe.haas.berkeley.edu/admissions/requirements',note:'需强量化背景：线代、多元微积分、微分方程、数值分析、概率统计，以及 C++ / Python。'},
    {id:'imperial',title:'Imperial · MSc Computing (AI & ML)',type:'海外硕博官方',period:'2027 入学',url:'https://www.imperial.ac.uk/study/courses/postgraduate-taught/computing-artificial-intelligence-msc/',note:'要求一等或等同学位，且须有大量计算机课程；不是零基础转专业项目。'},
    {id:'ucl',title:'UCL · MSc Data Science',type:'海外硕博官方',period:'当前官方页面',url:'https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc',note:'量化本科，数学、线代、概率统计及高阶语言编程基础。'},
    {id:'oxphd',title:'Oxford Statistics · 研究学位',type:'海外硕博官方',period:'当前官方页面',url:'https://www.stats.ox.ac.uk/study',note:'列出 DPhil Statistics 等；仅为研究方向例子，没有录取概率推断。'},
    {id:'ges',title:'HKU CEDARS · Graduate Employment Survey 2024',type:'毕业生调查',period:'2024 届',url:'https://www.cedars.hku.hk/index.php?hash=8c7b13271bb0416a858a1b2232c6709f&route=information/download',note:'全校月薪中位数 HK$27,600；平均 HK$33,492；商工就业板块平均 HK$28,431。不是专业细分起薪。'},
    {id:'mmtech',title:'Morgan McKinley · Technology Salary Guide',type:'职位薪酬',period:'2026 · HKD/月',url:'https://www.morganmckinley.com/hk/salary-guide/technology/permanent-salaries',note:'招聘公司职位 Low / Median / High；不同经验混合，不是毕业生薪资分布或保证。'},
    {id:'mmrisk',title:'Morgan McKinley · Risk & Compliance Salary Guide',type:'职位薪酬',period:'2026 · HKD/月',url:'https://www.morganmckinley.com/hk/salary-guide/legal-risk-compliance/permanent-salaries',note:'Quant Analyst 位于 Risk Management 栏；不能用来代表 hedge fund Quant Researcher 的总包。'},
    {id:'mmbank',title:'Morgan McKinley · Banking Salary Guide',type:'职位薪酬',period:'2026 · HKD/月',url:'https://www.morganmckinley.com/hk/salary-guide/banking-financial-services/permanent-salaries',note:'Investment Analyst 为职位市场基准，不是 IBGM / QFin 的应届生平均。'},
    {id:'randstad',title:'Randstad · Hong Kong Salary Guide 2025',type:'职位薪酬',period:'2025 · HKD/月 · PDF p29',url:'https://www.randstad.com.hk/s3fs-media/hk/public/2025-01/Randstad-Hong-Kong-SAR-2025-Job-Market-Outlook-Salary-Guide.pdf',note:'精算 Associate 区间；基础月薪，排除固定／浮动奖金。使用较旧年份，标注保留。'},
    {id:'blsds',title:'US BLS · Data Scientists',type:'海外职业统计',period:'May 2025 · USD/年',url:'https://www.bls.gov/ooh/math/data-scientists.htm',note:'美国全国全经验职业中位数，不是 HKU 毕业生数据。'},
    {id:'blscs',title:'US BLS · Software Developers',type:'海外职业统计',period:'May 2025 · USD/年',url:'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm',note:'软件开发职业中位数；排除用 QA/tester 中位数替代的混淆。'},
    {id:'blsact',title:'US BLS · Actuaries',type:'海外职业统计',period:'May 2025 · USD/年',url:'https://www.bls.gov/ooh/math/actuaries.htm',note:'合资格及其他经验阶段混合，不能等同精算本科应届起薪。'},
    {id:'blsfin',title:'US BLS · Financial Analysts',type:'海外职业统计',period:'May 2025 · USD/年',url:'https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm',note:'投资分析与金融风险职业分别记录；不作为量化研究员的直接代理。'},
    {id:'blsmgmt',title:'US BLS · Management Analysts',type:'海外职业统计',period:'May 2025 · USD/年',url:'https://www.bls.gov/ooh/business-and-financial/management-analysts.htm',note:'管理分析职业全国中位数，通常包含相关工作经验。'}
  ],
  masters: [
    {id:'msccs',name:'HKU MSc Computer Science',place:'香港',gate:'核对当届学术背景要求；建议备齐算法、数据结构、系统与编程课程。',focus:'计算机进阶 / 安全 / 金融计算',sources:['msccs']},
    {id:'mdasc',name:'HKU Master of Data Science',place:'香港',gate:'官方：微积分与代数、编程、初级统计三类各至少一门大学或专上课程。',focus:'数据建模与机器学习',sources:['mdasc']},
    {id:'mstat',name:'HKU Master of Statistics',place:'香港',gate:'官方：矩阵与微积分、初级统计、线性建模知识。',focus:'统计推断与应用',sources:['mstat']},
    {id:'mscai',name:'HKU MSc Artificial Intelligence',place:'香港',gate:'官方：线代、微积分、概率、初级统计、编程知识。',focus:'数学与 AI；2027–28 硕士全日制 1.5 年',sources:['mscai']},
    {id:'ftda',name:'HKU MSc FinTech & Data Analytics',place:'香港',gate:'先核对当届入学要求；建议补强数学、数据分析、编程与金融。',focus:'CDS 的科技与金融数据方向',sources:['pg']},
    {id:'ecic',name:'HKU MSc Electronic Commerce & Internet Computing',place:'香港',gate:'先核对当届入学要求；建议准备互联网系统、数字商业及项目经验。',focus:'互联网计算与数字商业',sources:['pg']},
    {id:'mfin',name:'HKU Master of Finance',place:'香港',gate:'核对当届要求；建议补金融、计量经济与定量课程。',focus:'金融进阶',sources:['mfin']},
    {id:'mfft',name:'HKU Master of Finance in FinTech',place:'香港',gate:'核对当届要求；建议补编程、金融与数据建模。',focus:'商学院 MFFinTech；与 CDS FTDA 分开',sources:['mfft']},
    {id:'mgm',name:'HKU Master of Global Management',place:'香港',gate:'核对当届要求；建议比较与本科内容的重叠及新增就业资源。',focus:'组织与全球管理',sources:['mgm']},
    {id:'mba',name:'HKU MBA（工作后）',place:'香港',gate:'官方：至少两年毕业后全职经验；另有 GMAT/GRE 等要求。',focus:'工作后转型 / 管理',sources:['mba']},
    {id:'oxstat',name:'Oxford MSc Statistical Science',place:'英国',gate:'官方：一等或等同学位，高阶数学与统计内容。',focus:'统计、计算与机器学习',sources:['oxstat']},
    {id:'oxfinance',name:'Oxford MSc Mathematical & Computational Finance',place:'英国',gate:'核对官方当届门槛；建议准备随机过程、数值方法、概率及金融计算。',focus:'数理金融',sources:['oxfinance']},
    {id:'berkeley',name:'Berkeley Haas Master of Financial Engineering',place:'美国',gate:'官方：线代、多元微积分、微分方程、数值分析、概率统计及 C++ / Python。',focus:'金融工程',sources:['berkeley']},
    {id:'imperial',name:'Imperial MSc Computing (AI & ML)',place:'英国',gate:'官方：一等或等同学位，且有大量计算机课程。',focus:'已有计算背景的 AI / ML 进阶',sources:['imperial']},
    {id:'ucl',name:'UCL MSc Data Science',place:'英国',gate:'官方：量化本科及数学、线代、概率统计、编程基础；通常至少 2:1 或等同。',focus:'统计与数据科学',sources:['ucl']}
  ],
  research: [
    {id:'computing',name:'HKU CDS · MPhil / PhD',fields:'CS、AI、机器学习、数据系统',gate:'须按学位与学院确认资格；研究课题、导师匹配、推荐信与研究经历是准备重点。授课硕士不是必经步骤。',sources:['rpg']},
    {id:'statistics',name:'HKU CDS · MPhil / PhD',fields:'统计、精算、风险、概率；海外例子 Oxford DPhil Statistics',gate:'建议准备高阶概率、统计推断、证明训练与研究项目；海外例子需另查资格、导师与资助。',sources:['rpg','oxphd']},
    {id:'business',name:'HKU Business · PhD',fields:'Finance / Management & Strategy / Innovation & Information Management',gate:'官方：一等本科或荣誉本科加硕士；GMAT/GRE、研究计划及学术推荐。没有研究硕士通常考虑四年 PhD。',sources:['businessphd','phdadmit']}
  ],
  roles: [
    {id:'software',name:'软件开发 · Full Stack Developer',hk:[30000,50000,70000],year:2026,source:'mmtech',us:135980,usLabel:'Software Developer',usSource:'blscs',note:'软件岗位例子；不是所有 CS 毕业生的去向。'},
    {id:'data',name:'Data Scientist · 数据科学',hk:[30000,50000,80000],year:2026,source:'mmtech',us:120230,usLabel:'Data Scientist',usSource:'blsds',note:'部分岗位偏好硕博；作品与工程／统计能力仍须验证。'},
    {id:'ml',name:'ML Engineer · 机器学习工程',hk:[35000,65000,90000],year:2026,source:'mmtech',us:null,note:'美国未填直接对应数据，不用 Data Scientist 中位数代替。'},
    {id:'analyst',name:'Data Analyst · 数据分析',hk:[23000,45000,70000],year:2026,source:'mmtech',us:null,note:'与 Data Scientist 分开；分析、SQL 与业务沟通经常是准备重点。'},
    {id:'risk',name:'Market Risk Analyst · 市场风险',hk:[25000,40000,50000],year:2026,source:'mmrisk',us:117330,usLabel:'Financial Risk Specialist（较宽职业口径）',usSource:'blsfin',note:'美国为较宽金融风险职业，非同一职位样本。'},
    {id:'quant',name:'Quant Analyst · 风险量化分析',hk:[35000,45000,60000],year:2026,source:'mmrisk',us:null,note:'来源属风险管理；不代表对冲基金研究／交易总包。'},
    {id:'actuarial',name:'Actuarial Associate · 精算',hk:[30000,35000,40000],year:2025,source:'randstad',us:130000,usLabel:'Actuary（全经验职业）',usSource:'blsact',note:'香港为 Associate 职级，2025 基础月薪；美国为全经验，口径不同。'},
    {id:'business',name:'IT Business Analyst · 商业分析',hk:[25000,45000,90000],year:2026,source:'mmtech',us:null,note:'偏 IT 的商业分析；不能替代一般管理培训生／战略咨询起薪。'},
    {id:'investment',name:'Investment Analyst · 投资分析',hk:[50000,60000,70000],year:2026,source:'mmbank',us:102740,usLabel:'Financial & Investment Analyst',usSource:'blsfin',note:'市场职位基准；金融机构、经验及奖金造成差异，不是应届工资。'},
    {id:'consulting',name:'战略咨询 / 管理培训生',hk:null,source:null,us:101860,usLabel:'Management Analyst（较宽职业口径）',usSource:'blsmgmt',note:'本次未取得可直接匹配的香港数字；海外较宽口径不用于香港定价。'},
    {id:'research',name:'量化研究员 / AI 研究员 / 博士后',hk:null,source:null,us:null,note:'职位差异大，缺少可比数据；不拿 Quant Analyst、助教津贴或教授工资填补。'}
  ],
  programmes: [
    {id:'cs',short:'Computer Science',zh:'计算机科学',code:'6999',degree:'BEng(CompSc)',group:'CDS',years:4,source:'cs',focus:['算法与数据结构','软件与系统','计算理论'],skills:['计算','工程'],patch:'面向 ML 加概率、线代和建模；面向 quant 加数理金融与 C++。第二专业可探索数学 / 统计 / 金融，须另查学分和资格。',masters:['msccs','mscai','mdasc','imperial','berkeley'],research:['computing','business'],roles:['software','ml','data','quant'],tradeoff:'技术出口广；AI 或金融方向需用选修与项目形成专长。',summary:'以计算机基础为主线，适合把系统与软件能力作为长期底盘。',delta:true},
    {id:'aids',short:'AI & Data Science',zh:'人工智能及数据科学',code:'6999',degree:'BEng(AI&DataSc)',group:'CDS',years:4,source:'cs',focus:['机器学习','数学与统计','数据驱动技术'],skills:['计算','统计','工程'],patch:'建议加强数据结构、系统、部署与研究项目；面向理论研究补概率及证明训练。第二专业可探索数学 / 统计。',masters:['mscai','mdasc','msccs','imperial','ucl'],research:['computing','statistics'],roles:['ml','data','software'],tradeoff:'目标更聚焦 AI；新课程的长期就业样本较少，官方所述 HKIE 认证为拟申请。',summary:'连接模型与计算，研究或工程出口取决于课程深度和项目质量。',delta:true},
    {id:'applied',short:'Applied Artificial Intelligence',zh:'应用人工智能',code:'6999',degree:'BASc(AppliedAI)',group:'CDS',years:4,source:'applied',focus:['Technology','Business & Finance','Medicine','Smart City','Neurocognitive Science'],skills:['计算','跨学科'],patch:'先确定一个应用领域，再补足算法、概率、数学与工程项目。Medicine concentration 不提供医生执业资格；跨至医疗 / 神经研究需学科先修。',masters:['mscai','mdasc','ucl','ftda','ecic'],research:['computing','statistics','business'],roles:['data','analyst','ml','business'],tradeoff:'跨域选择丰富；高级 ML / CS 硕士会检查实际计算课程，不能只靠 AI 名称。',summary:'五个应用 concentration；2027–28 已纳入 6999 共同收生。'},
    {id:'fintech',short:'Financial Technology',zh:'金融科技',code:'6248',degree:'BASc(FinTech)',group:'CDS',years:4,source:'fintech',focus:['计算与金融','数字金融应用','政策与监管'],skills:['计算','金融','跨学科'],patch:'先选技术开发、产品或金融模型主线。要走量化研究，建议补概率、随机过程、数值方法、C++ 与实证项目。',masters:['ftda','mfft','msccs','mfin','berkeley'],research:['computing','business'],roles:['software','business','quant','analyst'],tradeoff:'科技与金融之间灵活；须主动建立一侧深度，金融科技不等于量化金融。',summary:'CDS 与商学院合办，适合金融服务与技术应用的交叉方向。'},
    {id:'act',short:'Actuarial Science',zh:'精算学',code:'6729',degree:'BSc(ActuarSc)',group:'CDS',years:4,source:'act',focus:['概率与风险','保险与精算','金融与统计'],skills:['统计','金融','数学'],patch:'规划 IFoA / SOA 考试、实习与豁免条件；转向数据或量化工作可补 Python、机器学习与数值分析。',masters:['mstat','mfin','mdasc','oxstat','berkeley'],research:['statistics','business'],roles:['actuarial','risk','quant','data'],tradeoff:'职业资格路线清晰；资格考试与经验仍需投入，本科学位不等于精算师资格。',summary:'适合愿意长期投入专业考试、保险建模与风险分析的人。'},
    {id:'da',short:'Decision Analytics',zh:'决策分析',code:'6779',degree:'BStat · Professional Core DA',group:'CDS',years:4,source:'stat',focus:['统计与计算','机器学习','优化与决策'],skills:['统计','计算','数学'],patch:'建议补软件工程、数据库与部署；探索 CS / 数学 / 金融第二专业或 minor，但先核对重叠学分与先修。',masters:['mdasc','mstat','ucl','oxstat','berkeley'],research:['statistics','computing','business'],roles:['data','analyst','business','quant'],tradeoff:'宽而可定制：方向需要主动设计；数据分析基础不自动等于生产级 ML 工程能力。',summary:'以统计推理支持数据驱动决策；是专业核心，不是额外独立学位。'},
    {id:'rm',short:'Risk Management',zh:'风险管理',code:'6779',degree:'BStat · Professional Core RM',group:'CDS',years:4,source:'stat',focus:['统计建模','金融风险','量化分析'],skills:['统计','金融','数学'],patch:'建议补金融市场、计量、Python / C++ 与风险实习；专业资格须按目标岗位另行规划。',masters:['mstat','mfin','ftda','berkeley','oxfinance'],research:['statistics','business'],roles:['risk','quant','analyst'],tradeoff:'偏风险模型与金融应用；与前台量化交易、投资研究的招聘要求不同。',summary:'适合对不确定性、金融风险与模型验证感兴趣的路径。'},
    {id:'st',short:'Statistics',zh:'统计学',code:'6779',degree:'BStat · Professional Core ST',group:'CDS',years:4,source:'stat',focus:['统计推断','概率与数学','统计应用'],skills:['统计','数学'],patch:'面向博士补实分析、概率证明与研究；面向产业补 Python / R、SQL、数据工程与领域项目。',masters:['mstat','oxstat','mdasc','ucl','mscai'],research:['statistics','computing'],roles:['data','analyst','risk'],tradeoff:'理论与研究底盘强；技术产品出口要补系统与工程经历。',summary:'为统计研究、数据分析及跨行业定量工作建立基础。'},
    {id:'arts',short:'Arts + AI & Data Science',zh:'文学 + 人工智能及数据科学',code:'6298',degree:'BA & BEng(AI&DataSc)',group:'跨院',years:5,source:'arts',focus:['AI 与数据科学','人文与伦理','跨学科研究'],skills:['计算','跨学科','工程'],patch:'结合具体人文方向设计 AI 项目；申请计算硕士仍需足够数学、算法与系统课程。',masters:['mscai','mdasc','msccs','imperial','ecic'],research:['computing','business'],roles:['ml','data','software','business'],tradeoff:'五年双学位增加时间成本；人文交叉价值应与个人研究及职业目标相符。',summary:'CDS 相关跨院双学位，技术训练与人文判断并重。'},
    {id:'ibgm',short:'International Business & Global Management',zh:'国际商业及环球管理',code:'6896',degree:'BBA(IBGM)',group:'商学院',years:4,source:'ibgm',focus:['全球商业与管理','第二专业','海外交换'],skills:['商业','跨学科'],patch:'第二专业为必修。可探索 Finance / Economics / ISA 等；QFin 有额外甄选。转 DS / MFE 需补数学、统计、编程证据。',masters:['mgm','mfin','ecic','mba','mdasc'],research:['business'],roles:['consulting','business','investment'],tradeoff:'商业与国际视野强；第二专业决定技术深度，不能假定直接满足 CS / 量化硕士先修。',summary:'偏商业分析、咨询与管理；硕士或博士方向受第二专业与研究经历影响。'},
    {id:'qfin',short:'Quantitative Finance',zh:'计量金融',code:'6884',degree:'BSc(QFin)',group:'商学院',years:4,source:'qfin',focus:['金融与定价','数学与统计','金融编程'],skills:['金融','数学','计算'],patch:'面向量化研究加实分析、概率、随机过程、数值分析、C++ 与实证研究；面向金融实务强化实习与市场知识。',masters:['mfin','berkeley','oxfinance','mstat','mfft'],research:['business','statistics'],roles:['quant','risk','investment','research'],tradeoff:'金融与量化结合；顶级量化研究招聘通常还需很强数学、研究或工程证据。',summary:'从金融决策与建模切入；与 FinTech 的系统／应用侧重点不同。'}
  ]
};
