import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import { mkdtemp, writeFile, readFile, rename, unlink, readdir, rm, mkdir } from 'node:fs/promises';
import { chromium } from 'playwright-core';
import { createToolkit } from '../src/server.js';
import { findChromium } from '../src/core/pdf.js';

const folder = await mkdtemp(path.join(os.tmpdir(), 'toolkit-browser-'));
const filename = path.join(folder, 'a live document.md');
const evidence = '/tmp/toolkit-validation';
await mkdir(evidence, { recursive: true });
await writeFile(filename, '# Live document\n\nOriginal paragraph.\n\n## Details\n\n中文預覽與匯出。\n');
const app = await createToolkit({ port: 0, filename, interval: 100, baseDir: folder });
const browser = await chromium.launch({ executablePath: await findChromium(), headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
  const errors = [], external = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (!request.url().startsWith(new URL(app.url).origin) && !request.url().startsWith('data:') && request.url() !== 'about:blank') external.push(request.url()); });
  await page.goto(app.url);
  assert.equal(new URL(page.url()).hash, '');
  const preview = page.frameLocator('#preview');
  await preview.locator('h1').filter({ hasText: 'Live document' }).waitFor();
  assert.equal(await page.evaluate(() => document.cookie), ''); // Session cookie is HttpOnly.
  await page.reload();
  await preview.locator('h1').filter({ hasText: 'Live document' }).waitFor();
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).colorScheme), 'dark');
  assert.equal(await preview.locator('body').evaluate(body => getComputedStyle(body).backgroundColor), 'rgb(22, 22, 22)');
  const expandedLeft = await page.locator('main').evaluate(main => main.getBoundingClientRect().left);
  assert.ok(expandedLeft > 0);
  await page.getByRole('button', { name: 'Hide sidebar', exact: true }).click();
  assert.equal(await page.locator('#sidebar').isVisible(), false);
  assert.equal(await page.locator('main').evaluate(main => main.getBoundingClientRect().left), 0);
  assert.equal(await page.locator('#sidebar-toggle').getAttribute('aria-expanded'), 'false');
  assert.match(await preview.locator('h1').textContent(), /Live document/);
  await page.screenshot({ path: `${evidence}/sidebar-collapsed.png`, fullPage: true });
  await page.getByRole('button', { name: 'Show sidebar', exact: true }).click();
  assert.equal(await page.locator('#sidebar').isVisible(), true);
  await page.getByRole('button', { name: 'Source', exact: true }).click();
  assert.match(await page.locator('#source').textContent(), /Original paragraph/);
  await page.getByRole('button', { name: 'Preview', exact: true }).click();
  const before = Date.now();
  await writeFile(`${filename}.tmp`, '# Saved replacement\n\nThe next revision.\n\n## Details\n\n中文預覽與匯出。\n');
  await rename(`${filename}.tmp`, filename);
  await preview.locator('h1').filter({ hasText: 'Saved replacement' }).waitFor();
  const latency = Date.now() - before;
  await unlink(filename);
  await page.locator('#message').filter({ hasText: 'File is missing' }).waitFor();
  assert.equal(await page.locator('#export-button').isDisabled(), true);
  await writeFile(filename, '# Restored document\n\nBack after deletion.\n\n## Details\n\n中文預覽與匯出。\n');
  await preview.locator('h1').filter({ hasText: 'Restored document' }).waitFor();
  await page.locator('#filepath').fill(path.join(folder, 'missing.md'));
  await page.getByRole('button', { name: 'Open file' }).click();
  await page.locator('#message').filter({ hasText: 'File not found' }).waitFor();
  assert.match(await preview.locator('h1').textContent(), /Restored document/);
  await page.locator('#filepath').fill(filename);
  await page.getByRole('button', { name: 'Open file' }).click();
  await page.waitForFunction(() => document.querySelector('#message').hidden);
  assert.deepEqual(await readdir(folder), ['a live document.md']);
  const savedSource = await readFile(filename, 'utf8');
  await page.screenshot({ path: `${evidence}/desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Hide sidebar', exact: true }).click();
  assert.equal(await page.locator('#sidebar').isVisible(), false);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: `${evidence}/mobile.png`, fullPage: true });
  await page.getByRole('button', { name: 'Show sidebar', exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1100 });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export PDF' }).click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(), 'a live document.pdf');
  await download.saveAs(`${evidence}/export.pdf`);
  const pdf = await readFile(`${evidence}/export.pdf`);
  assert.equal(pdf.subarray(0, 5).toString(), '%PDF-');
  assert.equal(await readFile(filename, 'utf8'), savedSource);
  assert.deepEqual(await readdir(folder), ['a live document.md']);
  // Exercise a representative document with tables, code, task lists and CJK text.
  const samplePath = new URL('../examples/welcome.md', import.meta.url).pathname;
  await page.locator('#filepath').fill(samplePath);
  await page.getByRole('button', { name: 'Open file' }).click();
  await preview.locator('h1').filter({ hasText: 'A page in the making' }).waitFor();
  await page.screenshot({ path: `${evidence}/sample-desktop.png`, fullPage: true });
  await page.locator('#paper').selectOption('Letter');
  const sampleDownloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export PDF' }).click();
  await (await sampleDownloadPromise).saveAs(`${evidence}/sample-letter.pdf`);
  for (const background of ['yellow', 'black']) {
    await page.getByLabel('PDF background', { exact: true }).selectOption(background);
    const requestPromise = page.waitForRequest(request => request.url().endsWith('/api/export/pdf'));
    const coloredDownloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export PDF' }).click();
    assert.equal((await requestPromise).postDataJSON().background, background);
    await (await coloredDownloadPromise).saveAs(`${evidence}/sample-${background}.pdf`);
  }
  assert.deepEqual(errors, []);
  assert.deepEqual(external, []);
  console.log(JSON.stringify({ result: 'PASS', latencyMs: latency, pdfBytes: pdf.length, checks: ['bare URL and reload with automatic HttpOnly session', 'dark interface and document', 'sidebar fully collapses and reopens on desktop/mobile', 'atomic save', 'source view', 'delete/recreate recovery', 'invalid path retains preview', 'manual A4 and Letter PDF downloads', 'white/yellow/black PDF controls', 'table/code/task/CJK document', 'source unchanged', 'no document cache files', 'mobile width', 'no external requests', 'no browser errors'], evidence }, null, 2));
} finally {
  await browser.close(); await app.close(); await rm(folder, { recursive: true, force: true });
}
