// Descriptions checked against the linked repository READMEs on 2026-10-02.
// Visuals and inspiration prompts are original Gitpop editorial content.
export const categories = ['All discoveries', '3D & WebGL', 'Animation', 'Creative coding', 'UI experiments'];
export const repos = [
  { id: 'mukes555/3d-shape-particle-text', title: 'A brain made of particles.', name: '3d-shape-particle-text', category: '3D & WebGL', language: 'JavaScript', tags: ['Three.js', 'Particles', 'React'], visual: 'brain', color: '#b9ee88', description: 'Thousands of points, endless shapes. A React + Three.js component that morphs 3D particles into brains, spirals, and custom text.', spark: 'What if your next landing page could think? Turn a static hero into a living particle sculpture that responds to curiosity.', caption: 'a thousand points. one possibility.' },
  { id: 'PavelDoGreat/WebGL-Fluid-Simulation', title: 'Let your ideas flow.', name: 'WebGL-Fluid-Simulation', category: 'Creative coding', language: 'JavaScript', tags: ['WebGL', 'Simulation', 'Interactive'], visual: 'fluid', color: '#b3a4ff', description: 'An interactive fluid simulation that brings swirls of color to your browser, with support for mobile touch.', spark: 'Make a digital canvas feel like liquid. Try a cursor trail, an ambient album cover, or a paint playground you can get lost in.', caption: 'a little chaos. a lot of color.' },
  { id: 'pmndrs/react-three-fiber', title: 'A whole new dimension.', name: 'react-three-fiber', category: '3D & WebGL', language: 'TypeScript', tags: ['React', 'Three.js', '3D'], visual: 'orbit', color: '#f0ae77', description: 'Build interactive Three.js scenes with reusable React components. A bridge between familiar UI code and a world of 3D.', spark: 'Take your UI off the flat page. Build a tiny solar system, a playful product scene, or a portfolio with a world inside it.', caption: 'ordinary components. extraordinary worlds.' },
  { id: 'mrdoob/three.js', title: 'Build a tiny universe.', name: 'three.js', category: '3D & WebGL', language: 'JavaScript', tags: ['3D', 'WebGL', 'WebGPU'], visual: 'orbit', color: '#b9ee88', description: 'A JavaScript 3D library for building scenes, objects, lighting, and interactive experiences right in the browser.', spark: 'Start small: one orbiting object, one surprising material, one interaction. Let that experiment grow into a world.', caption: 'the browser is your universe.' },
  { id: 'processing/p5.js', title: 'Code outside the lines.', name: 'p5.js', category: 'Creative coding', language: 'JavaScript', tags: ['Generative art', 'Canvas', 'Creative coding'], visual: 'flow', color: '#ef91ad', description: 'A welcoming creative coding library for artists, designers, and anyone who wants to make expressive things on the web.', spark: 'Give a simple rule room to surprise you. Make a generative poster that changes with the time, weather, or a friend’s initials.', caption: 'a few rules. infinite outcomes.' },
  { id: 'juliangarnier/anime', title: 'Give pixels personality.', name: 'anime', category: 'Animation', language: 'JavaScript', tags: ['Animation', 'SVG', 'Motion'], visual: 'wave', color: '#b3a4ff', description: 'A JavaScript animation engine for bringing movement to web interfaces, SVG illustrations, and creative experiments.', spark: 'Make the ordinary feel delightful. Choreograph a loading state, animate a doodle, or make a button feel like it has a heartbeat.', caption: 'good timing changes everything.' },
  { id: 'codrops/ParticleEffectsButtons', title: 'Buttons with a little burst.', name: 'ParticleEffectsButtons', category: 'UI experiments', language: 'JavaScript', tags: ['Particles', 'Microinteractions', 'Buttons'], visual: 'burst', color: '#f0ae77', description: 'A little library that turns buttons and other elements into bursts of particles. A playful experiment from Codrops.', spark: 'Celebrate a tiny win. Let a completed task dissolve into confetti or make a “send” button scatter like a paper plane.', caption: 'small interactions. big smiles.' },
  { id: 'pmndrs/drei', title: 'A shortcut to wonder.', name: 'drei', category: '3D & WebGL', language: 'TypeScript', tags: ['React Three Fiber', '3D', 'Helpers'], visual: 'orbit', color: '#b3a4ff', description: 'A collection of helpers for React Three Fiber, making it easier to add useful building blocks to your 3D scenes.', spark: 'Skip the blank canvas feeling. Combine a few 3D helpers into a dreamy product display or a miniature interactive diorama.', caption: 'a head start for your imagination.' },
  { id: 'oframe/ogl', title: 'Less code. More dimension.', name: 'ogl', category: '3D & WebGL', language: 'JavaScript', tags: ['WebGL', 'Shaders', 'Minimal'], visual: 'wave', color: '#89c9e9', description: 'A minimal WebGL library that keeps the rendering tools close at hand for custom graphics and shader experiments.', spark: 'Let the material be the story. Explore a rippling plane, a glassy distortion, or a shader that reacts to the mouse.', caption: 'lightweight tools. heavyweight ideas.' },
  { id: 'codrops/GooeyTextHoverEffect', title: 'Type that breaks the mold.', name: 'GooeyTextHoverEffect', category: 'UI experiments', language: 'HTML', tags: ['Typography', 'SVG filters', 'Hover effects'], visual: 'type', color: '#b9ee88', description: 'An experimental gooey text hover effect using SVG filters. A small study in giving typography a surprising texture.', spark: 'Treat type like a material. Make a word stretch, melt, or wobble when someone reaches for it.', caption: 'words with a mind of their own.' },
  { id: 'motiondivision/motion', title: 'Make every move count.', name: 'motion', category: 'Animation', language: 'TypeScript', tags: ['Motion', 'React', 'Interactions'], visual: 'wave', color: '#ef91ad', description: 'A modern animation library for JavaScript and React, built to bring movement and interaction to web experiences.', spark: 'Connect two states with a story. Try a card that opens into a page or a gallery that feels like a stack of physical prints.', caption: 'from one moment to the next.' },
  { id: 'tsparticles/tsparticles', title: 'A constellation of ideas.', name: 'tsparticles', category: 'Creative coding', language: 'TypeScript', tags: ['Particles', 'Confetti', 'Backgrounds'], visual: 'burst', color: '#89c9e9', description: 'Customizable particle effects, animated backgrounds, confetti, and fireworks, with integrations for popular web frameworks.', spark: 'Build a backdrop with a pulse. Connect particles into a constellation or add a little celebration to a finished creation.', caption: 'leave a little room for magic.' },
];

export function filterRepos(category) {
  return category === categories[0] ? repos : repos.filter(repo => repo.category === category);
}

// Shuffle bag: every eligible repo appears once before the next cycle starts.
export function makeBag(pool, currentId, random = Math.random) {
  const bag = [...pool];
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [bag[i], bag[j]] = [bag[j], bag[i]];
  }
  if (bag.length > 1 && bag.at(-1).id === currentId) [bag[0], bag[bag.length - 1]] = [bag.at(-1), bag[0]];
  return bag;
}
