const pair = (en, zh) => ({ en, zh });
export const lessons = [
  {
    id:'vectors', group:'Linear algebra', title:'Meet the vector', zh:'由向量開始', time:10, lab:'vectors',
    subtitle:pair('A few numbers. One direction. A whole new way to think.','幾個數字、一個方向，開啟新的思考方式。'),
    idea:pair('A vector is an ordered list of numbers. In geometry, you can draw it as an arrow: its coordinates tell you how far to move along each axis. In data, those same coordinates can represent different features, such as hours studied and test marks.','向量是一組有次序的數字。幾何上，它是一支箭嘴：座標告訴你沿每條軸走多遠。在數據中，各分量也可代表溫習時數、測驗分數等不同特徵。'),
    formula:String.raw`\mathbf v=\begin{bmatrix}x\\y\end{bmatrix},\qquad \|\mathbf v\|=\sqrt{x^2+y^2}`,
    meaning:pair('The brackets keep the components together. The double bars mean length, so Pythagoras is already doing linear algebra.','方括號把分量組合起來；雙直線表示長度。你熟悉的畢氏定理已經在線性代數中派上用場。'),
    steps:[pair('Start with v = (3, 2): walk 3 right and 2 up.','從 v = (3, 2) 開始：向右 3，向上 2。'),pair('Change the scale to 2. Every component doubles; the direction stays the same.','把倍數調至 2。每個分量加倍，方向不變。'),pair('Try a negative scale, then switch to 3D and change z.','試負倍數，再切換至 3D 並改變 z。')],
    example:pair('For v = (3, 4), the length is √(9 + 16) = 5. Multiplying by −2 gives (−6, −8), length 10, pointing the opposite way. A zero vector has length 0 and no direction.','v = (3, 4) 的長度是 √(9 + 16) = 5。乘以 −2 得 (−6, −8)，長度為 10，方向相反。零向量長度為 0，沒有方向。'),
    trap:pair('A vector is not just its length: (3, 4) and (−3, −4) have the same length but opposite directions.','向量不只是長度：(3, 4) 和 (−3, −4) 長度相同，方向卻相反。'),
    quiz:{q:pair('What is −2 × (3, −1)?','−2 × (3, −1) 是甚麼？'),options:['(−6, 2)','(6, −2)','(1, −3)'],answer:0,why:pair('Multiply each component by −2. Negative scaling reverses the arrow.','把每個分量乘以 −2。負倍數會令箭嘴反向。')},
    ref:'Strang §1.1, printed pp. 2–10',
    py:'import numpy as np\nv = np.array([3., 4.])\nprint(-2 * v)              # [-6. -8.]\nprint(np.linalg.norm(v))    # 5.0',
    r:'v <- c(3, 4)\nprint(-2 * v)              # -6 -8\nprint(sqrt(sum(v^2)))       # 5'
  },
  {
    id:'span',group:'Linear algebra',title:'Build a space',zh:'組合出一個空間',time:12,lab:'span',
    subtitle:pair('Addition, span, and why a basis matters.','向量相加、張成空間，以及基底的意義。'),
    idea:pair('Add arrows by placing the second at the tip of the first. A linear combination scales arrows and then adds them. The span is every point you can reach by choosing any real coefficients. Two non-parallel vectors span the whole 2D plane.','把第二支箭嘴放在第一支的末端，就能相加。線性組合先把向量乘以倍數，再相加。張成空間是任意實數倍數下所有能到達的位置。兩個不平行的向量可以張成整個二維平面。'),
    formula:String.raw`\mathbf w=c_1\mathbf u+c_2\mathbf v,\qquad \operatorname{span}(\mathbf u,\mathbf v)=\{c_1\mathbf u+c_2\mathbf v:c_1,c_2\in\mathbb R\}`,
    meaning:pair('A basis is a set that spans the space without redundant vectors. The coefficients are coordinates relative to that basis. Dimension counts the number of basis vectors.','基底是一組能張成空間、又沒有多餘向量的向量。倍數就是相對該基底的座標；維度是基底向量的數目。'),
    steps:[pair('Change c₁ and c₂ and watch the head-to-tail construction.','調整 c₁ 和 c₂，觀察首尾相接的組合。'),pair('Choose “Dependent”: both arrows now lie on one line.','選「線性相關」：兩支箭嘴現在在同一直線上。'),pair('Switch to 3D. Two independent vectors still span only a plane.','切換至 3D：兩個獨立向量仍然只張成一個平面。')],
    example:pair('With u = (1, 0) and v = (0, 1), 3u + 2v = (3, 2). With u = (1, 1) and v = (2, 2), every combination has equal x and y coordinates. You can never reach (1, 0).','u = (1, 0)、v = (0, 1) 時，3u + 2v = (3, 2)。若 u = (1, 1)、v = (2, 2)，所有組合的 x、y 都相等，永遠到不了 (1, 0)。'),
    trap:pair('The visible patch is only a finite illustration. A span uses all real coefficients and extends indefinitely.','圖中只展示有限範圍；張成空間容許所有實數倍數，會無限延伸。'),
    quiz:{q:pair('What is the dimension of span((1, 2), (2, 4))?','span((1, 2), (2, 4)) 的維度是多少？'),options:['0','1','2'],answer:1,why:pair('The second vector is twice the first. There is only one independent direction.','第二個向量是第一個的兩倍，只有一個獨立方向。')},ref:'Strang §1.1 and §3.5, printed p. 169',
    py:'import numpy as np\nu, v = np.array([1, 1]), np.array([2, 2])\nB = np.column_stack([u, v])\nprint(3*u - v)             # [1 1]\nprint(np.linalg.matrix_rank(B))  # 1',
    r:'u <- c(1, 1); v <- c(2, 2)\nB <- cbind(u, v)\nprint(3*u - v)             # 1 1\nprint(qr(B)$rank)           # 1'
  },
  {
    id:'dot',group:'Linear algebra',title:'Measure alignment',zh:'內積與投影',time:12,lab:'dot',
    subtitle:pair('The dot product turns direction into a number.','內積把方向關係變成一個數字。'),
    idea:pair('The dot product measures how much two vectors point together. It is positive for acute angles, zero for perpendicular nonzero vectors, and negative for obtuse angles. Projection finds the closest point on a line through the origin.','內積量度兩個向量有多「同方向」：夾角為銳角時為正，兩個非零向量垂直時為零，鈍角時為負。投影找出過原點直線上最接近原向量的位置。'),
    formula:String.raw`\mathbf v\cdot\mathbf u=\sum_i v_i u_i=\|\mathbf v\|\|\mathbf u\|\cos\theta,\qquad \operatorname{proj}_{\mathbf u}\mathbf v=\frac{\mathbf v\cdot\mathbf u}{\mathbf u\cdot\mathbf u}\mathbf u`,
    meaning:pair('Projection requires u ≠ 0. The leftover vector v − projᵤ(v) is perpendicular to u. This is the geometry behind least squares.','投影方向 u 必須非零。剩餘向量 v − projᵤ(v) 與 u 垂直，這正是最小二乘法的幾何基礎。'),
    steps:[pair('Move v while keeping u fixed. Watch the dashed perpendicular.','固定 u，移動 v，觀察垂直虛線。'),pair('Make the dot product negative by moving v to the other side.','把 v 移到另一側，使內積變成負數。'),pair('Try u = (0, 0) and notice why projection becomes undefined.','試 u = (0, 0)，看看為何投影未定義。')],
    example:pair('For v = (3, 2) and u = (1, 0), v·u = 3 and projᵤ(v) = (3, 0). The residual (0, 2) is perpendicular to the x-axis.','v = (3, 2)、u = (1, 0) 時，v·u = 3，投影為 (3, 0)。殘差 (0, 2) 垂直於 x 軸。'),
    trap:pair('The dot product is a scalar, not a vector. The zero vector has dot product zero with every vector, but its angle is undefined.','內積是純量，不是向量。零向量與所有向量的內積都是零，但其夾角未定義。'),
    quiz:{q:pair('Find (2, 1) · (−1, 2).','求 (2, 1) · (−1, 2)。'),options:['−4','0','4'],answer:1,why:pair('2(−1) + 1(2) = 0, so these two nonzero vectors are perpendicular.','2(−1) + 1(2) = 0，所以這兩個非零向量互相垂直。')},ref:'Strang §1.2 and §4.2, printed pp. 11, 207',
    py:'import numpy as np\nv, u = np.array([3., 2.]), np.array([1., 0.])\np = (v @ u)/(u @ u) * u\nprint(p, (v-p) @ u)        # [3. 0.] 0.0',
    r:'v <- c(3, 2); u <- c(1, 0)\np <- sum(v*u)/sum(u*u) * u\nprint(p)                   # 3 0\nprint(sum((v-p)*u))         # 0'
  },
  {
    id:'matrices',group:'Linear algebra',title:'A matrix moves space',zh:'矩陣如何改變空間',time:15,lab:'matrix',
    subtitle:pair('See the columns. Understand the transformation.','看懂每一列，就看懂變換。'),
    idea:pair('A matrix is a rectangular array of numbers. An m × n matrix takes an n-component input to an m-component output. In a 2 × 2 transformation, the first column tells you where (1, 0) goes and the second tells you where (0, 1) goes. Every other arrow follows by linear combination.','矩陣是長方形排列的數字。m × n 矩陣把 n 個分量的輸入轉成 m 個分量的輸出。二階方陣的第一列表示 (1, 0) 的去向，第二列表示 (0, 1) 的去向；其他向量的去向由線性組合決定。'),
    formula:String.raw`A\mathbf v=\begin{bmatrix}a&b\\c&d\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix}=x\begin{bmatrix}a\\c\end{bmatrix}+y\begin{bmatrix}b\\d\end{bmatrix}`,
    meaning:pair('Multiplication is row-by-column. A linear transformation keeps the origin fixed and preserves addition and scalar multiplication. A translation needs an extra construction, such as homogeneous coordinates.','乘法按橫行乘直列計算。線性變換固定原點，保留向量相加及純量乘法。平移需要額外的表示法，例如齊次座標。'),
    steps:[pair('Pick a shear: vertical grid lines tilt while horizontal ones stay level.','選「剪切」：垂直網格線傾斜，水平線保持水平。'),pair('Move the blend slider between the identity and your matrix.','用變換進度滑桿，在單位矩陣與你的矩陣之間探索。'),pair('Edit any entry, then try 3D to transform a unit cube.','修改任何元素，再試 3D，把單位立方體變換。')],
    example:pair('For A = [[1, 1], [0, 1]] and v = (2, 1), Av = (3, 1). The y-coordinate contributes one extra unit to x. This is a shear, not a rotation.','A = [[1, 1], [0, 1]]、v = (2, 1) 時，Av = (3, 1)。y 分量為 x 增加了一個單位，這是剪切。'),
    trap:pair('Read dimensions as rows × columns. For AB, the number of columns of A must match the number of rows of B.','尺寸讀作「橫行數 × 直列數」。計算 AB 時，A 的直列數須等於 B 的橫行數。'),
    quiz:{q:pair('What does [[2, 0], [0, 3]] do to (1, 2)?','[[2, 0], [0, 3]] 把 (1, 2) 變成甚麼？'),options:['(2, 6)','(3, 5)','(2, 3)'],answer:0,why:pair('The x-coordinate doubles and the y-coordinate triples.','x 座標乘以 2，y 座標乘以 3。')},ref:'Strang §1.3 and §7.1, printed pp. 22, 376',
    py:'import numpy as np\nA = np.array([[1, 1], [0, 1]])\nv = np.array([2, 1])\nprint(A @ v)               # [3 1]\n# A * v is elementwise broadcasting, not matrix multiplication.',
    r:'A <- matrix(c(1, 1, 0, 1), nrow=2, byrow=TRUE)\nv <- c(2, 1)\nprint(A %*% v)             # 3, 1\n# A * A multiplies entries; A %*% A multiplies matrices.'
  },
  {
    id:'composition',group:'Linear algebra',title:'Order changes the answer',zh:'矩陣乘法的次序',time:10,lab:'composition',
    subtitle:pair('Two transformations, one combined matrix.','兩次變換，合成一個矩陣。'),
    idea:pair('In ABv, B acts first and A acts second. Matrix multiplication composes transformations. Stretching and then rotating can give a different result from rotating and then stretching. Usually AB ≠ BA.','在 ABv 中，B 先作用，A 後作用。矩陣乘法把變換合成。先拉伸後旋轉，與先旋轉後拉伸的結果可以不同，通常 AB ≠ BA。'),
    formula:String.raw`A(B\mathbf v)=(AB)\mathbf v,\qquad (AB)_{ij}=\sum_k A_{ik}B_{kj}`,
    meaning:pair('The rightmost transformation happens first. Multiplication is associative, so parentheses may move, but the order may not.','最右邊的變換最先發生。矩陣乘法有結合律，可以改括號的位置，但不能隨意調換次序。'),
    steps:[pair('Change the horizontal stretch and rotation angle.','改變水平拉伸倍數與旋轉角度。'),pair('Compare A(Bv) and B(Av) on the same diagram.','在同一圖中比較 A(Bv) 與 B(Av)。'),pair('Set equal stretch factors: uniform scaling commutes with rotation.','把兩個拉伸倍數設為相同：等比例縮放與旋轉可以交換次序。')],
    example:pair('Let A stretch x by 2, B rotate 90°, and v = (1, 1). ABv = (−2, 1), but BAv = (−1, 2).','A 把 x 拉伸 2 倍，B 旋轉 90°，v = (1, 1)。ABv = (−2, 1)，BAv = (−1, 2)。'),
    trap:pair('In NumPy use @; in R use %*%. The * operator in either language multiplies entries instead.','NumPy 用 @；R 用 %*%。兩者的 * 都是逐元素乘法。'),
    quiz:{q:pair('In ABv, which transformation acts first?','在 ABv 中，哪個變換先作用？'),options:['A','B','Both simultaneously / 同時'],answer:1,why:pair('Read the actions from right to left: v → Bv → A(Bv).','由右至左讀：v → Bv → A(Bv)。')},ref:'Strang §2.4, printed p. 68',
    py:'import numpy as np\nA = np.diag([2, 1])\nB = np.array([[0, -1], [1, 0]])\nv = np.array([1, 1])\nprint(A @ B @ v, B @ A @ v)  # [-2 1], [-1 2]',
    r:'A <- diag(c(2, 1))\nB <- matrix(c(0, -1, 1, 0), 2, byrow=TRUE)\nv <- c(1, 1)\nprint(A %*% B %*% v)       # -2, 1\nprint(B %*% A %*% v)       # -1, 2'
  },
  {
    id:'systems',group:'Linear algebra',title:'Solve the intersection',zh:'聯立方程的幾何',time:15,lab:'systems',
    subtitle:pair('From familiar simultaneous equations to Ax = b.','從熟悉的聯立方程走到 Ax = b。'),
    idea:pair('Each equation in two unknowns is usually a line. A solution lies on both lines. In matrix language, solving Ax = b asks which combination of the columns of A reaches b. Elimination subtracts a multiple of one equation from another to remove an unknown.','二元一次方程通常代表一條直線，解在兩線上。矩陣語言中，解 Ax = b 就是找出 A 的直列如何組合成 b。消元法把一條方程的倍數從另一條減去，消除一個未知數。'),
    formula:String.raw`\begin{cases}ax+by=p\\cx+dy=q\end{cases}\quad\Longleftrightarrow\quad\begin{bmatrix}a&b\\c&d\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}p\\q\end{bmatrix}`,
    meaning:pair('Independent equations give a unique solution. Parallel distinct lines give no solution. Coincident lines give infinitely many. Zero rows need care: 0 = 0 adds no constraint; 0 = 1 is impossible.','獨立方程有唯一解；平行而不同的直線無解；重合直線有無限多解。零橫行要小心：0 = 0 沒有增加限制，0 = 1 則不可能。'),
    steps:[pair('Start with the unique-solution preset and inspect the intersection.','先選唯一解，觀察交點。'),pair('Switch to parallel, then coincident equations.','切換至平行，再切換至重合方程。'),pair('Change the constants on the right without changing A.','保持 A 不變，只改右邊的常數。')],
    example:pair('x + y = 3 and x − y = 1. Subtract the second equation from the first: 2y = 2, so y = 1. Substitute back to get x = 2. In code, solve the system directly rather than explicitly forming A⁻¹.','x + y = 3、x − y = 1。第一式減第二式得 2y = 2，即 y = 1；代回得 x = 2。編程時直接求解，通常比先計算 A⁻¹ 更合適。'),
    trap:pair('A singular matrix does not automatically mean no solution. It can also mean infinitely many solutions.','奇異矩陣不一定無解，也可能有無限多解。'),
    quiz:{q:pair('x + y = 2 and 2x + 2y = 5 have…','x + y = 2 和 2x + 2y = 5 有⋯'),options:['One solution / 一個解','No solution / 無解','Infinitely many / 無限多解'],answer:1,why:pair('Doubling the first equation gives 2x + 2y = 4, which contradicts 5.','把第一式乘以 2 得 2x + 2y = 4，與第二式矛盾。')},ref:'Strang §2.1–2.2, printed pp. 31, 45',
    py:'import numpy as np\nA = np.array([[1., 1.], [1., -1.]])\nb = np.array([3., 1.])\nx = np.linalg.solve(A, b)\nprint(x, A @ x)            # [2. 1.], [3. 1.]',
    r:'A <- matrix(c(1, 1, 1, -1), 2, byrow=TRUE)\nb <- c(3, 1)\nx <- solve(A, b)\nprint(x)                   # 2 1\nprint(A %*% x)             # 3, 1'
  },
  {
    id:'determinants',group:'Linear algebra',title:'Area tells a story',zh:'行列式與面積',time:12,lab:'determinant',
    subtitle:pair('Stretch, flip, or collapse: read the determinant.','拉伸、翻轉、壓扁：用行列式讀懂。'),
    idea:pair('A 2 × 2 matrix transforms a unit square into a parallelogram. Its determinant is the signed area scale factor. Magnitude measures area change; a negative sign indicates a reversal of orientation. Zero means the plane collapses to a line or point.','二階方陣把單位正方形變成平行四邊形。行列式是帶符號的面積倍數：絕對值量度面積變化，負號表示方向翻轉，零表示平面被壓成直線或點。'),
    formula:String.raw`\det\begin{bmatrix}a&b\\c&d\end{bmatrix}=ad-bc,\qquad A^{-1}=\frac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}\ \ (ad-bc\ne0)`,
    meaning:pair('For a square matrix, a nonzero determinant means an inverse exists. In 3D, the determinant describes signed volume scaling.','方陣的行列式非零，就存在逆矩陣。三維中，行列式表示帶符號的體積倍數。'),
    steps:[pair('Choose stretch and compare the original unit square with its image.','選拉伸，比較單位正方形與變換後的圖形。'),pair('Choose reflection and watch the sign change.','選反射，觀察符號改變。'),pair('Choose collapse: area vanishes and the inverse disappears.','選壓扁：面積變為零，逆矩陣不再存在。')],
    example:pair('A = [[2, 0], [0, 3]] has det A = 6: areas become six times as large. A = [[1, 2], [2, 4]] has determinant 0 because its columns are dependent.','A = [[2, 0], [0, 3]] 的行列式為 6，面積變成六倍。A = [[1, 2], [2, 4]] 的直列線性相關，行列式為 0。'),
    trap:pair('The blend slider shows (1 − t)I + tA. This is a linear interpolation of entries, not necessarily a pure rotation or a path of invertible matrices.','進度滑桿表示 (1 − t)I + tA，是矩陣元素的線性插值；途中不一定是純旋轉，也不一定一直可逆。'),
    quiz:{q:pair('If det A = −3, the transformed unit square has area…','若 det A = −3，變換後的單位正方形面積為⋯'),options:['−3','3','1/3'],answer:1,why:pair('Geometric area is |det A| = 3. The sign records orientation.','幾何面積是 |det A| = 3；符號記錄方向。')},ref:'Strang §5.1 and §2.5, printed pp. 245, 82',
    py:'import numpy as np\nA = np.diag([2., 3.])\nprint(np.linalg.det(A))     # approximately 6\nprint(np.linalg.inv(A))     # diagonal: 0.5, 1/3',
    r:'A <- diag(c(2, 3))\nprint(det(A))              # 6\nprint(solve(A))            # inverse: diagonal 0.5, 1/3'
  },
  {
    id:'eigen',group:'Linear algebra',title:'Find a steady direction',zh:'特徵向量與特徵值',time:15,lab:'eigen',
    subtitle:pair('Some arrows keep their line under a transformation.','某些箭嘴在變換後，仍沿同一直線。'),
    idea:pair('An eigenvector is a nonzero vector whose image is a scalar multiple of itself. Its line stays fixed, even if the arrow stretches, reverses, or becomes zero. The eigenvalue is that scale factor.','特徵向量是非零向量，其變換結果是本身的純量倍數。所在直線保持不變，但箭嘴可以伸長、反向，甚至變為零。特徵值就是該倍數。'),
    formula:String.raw`A\mathbf v=\lambda\mathbf v,\quad \mathbf v\ne\mathbf0,\qquad \det(A-\lambda I)=0`,
    meaning:pair('Subtract λv, then look for a nonzero solution of (A − λI)v = 0. That requires A − λI to be singular. Some real matrices have no real eigenvectors; a 90° rotation is one example.','把 λv 移到左邊，找 (A − λI)v = 0 的非零解，就要求 A − λI 奇異。有些實矩陣沒有實特徵向量，例如旋轉 90°。'),
    steps:[pair('Use stretch and rotate the input direction until the two arrows align.','選拉伸，轉動輸入方向，直到兩支箭嘴共線。'),pair('Try reflection: an eigenvalue can be negative.','試反射：特徵值可以為負。'),pair('Try a 90° rotation and search for a real steady direction.','試旋轉 90°，找找有沒有實數的固定方向。')],
    example:pair('For diag(2, 1), (1, 0) is an eigenvector with λ = 2, and (0, 1) has λ = 1. Any nonzero multiple of an eigenvector is also an eigenvector.','對 diag(2, 1)，(1, 0) 的特徵值為 2，(0, 1) 的特徵值為 1。特徵向量的任何非零倍數仍是特徵向量。'),
    trap:pair('The zero vector is never an eigenvector. A repeated eigenvalue does not guarantee enough independent eigenvectors to diagonalize a matrix.','零向量永遠不是特徵向量。重複特徵值也不保證有足夠獨立特徵向量把矩陣對角化。'),
    quiz:{q:pair('For A = diag(3, −2), what is the eigenvalue of (0, 1)?','A = diag(3, −2) 時，(0, 1) 的特徵值是多少？'),options:['3','−2','0'],answer:1,why:pair('A(0, 1) = (0, −2) = −2(0, 1).','A(0, 1) = (0, −2) = −2(0, 1)。')},ref:'Strang §6.1, printed p. 284',
    py:'import numpy as np\nA = np.diag([2., 1.])\nvalues, vectors = np.linalg.eig(A)\nprint(values)              # [2. 1.]\n# Eigenvectors are the COLUMNS of vectors.',
    r:'A <- diag(c(2, 1))\nresult <- eigen(A)\nprint(result$values)       # 2 1\n# Eigenvectors are the columns of result$vectors.'
  },
  {
    id:'summary',group:'Statistics',title:'Get to know your data',zh:'認識數據的中心與分散',time:10,lab:'summary',
    subtitle:pair('Mean, median, and spread — with an outlier you control.','平均數、中位數、分散程度：親手移動離群值。'),
    idea:pair('A mean balances the values; a median splits sorted data in half. Variance measures squared distance from the mean. Standard deviation brings that spread back to the original units. A histogram shows shape that one summary number can miss.','平均數平衡所有數值；中位數把排序後的數據分成兩半。方差量度數值離平均數的平方距離；標準差把尺度帶回原本的單位。直方圖展示單一統計量無法表達的形狀。'),
    formula:String.raw`\bar x=\frac1n\sum_{i=1}^n x_i,\qquad s^2=\frac1{n-1}\sum_{i=1}^n(x_i-\bar x)^2,\qquad s=\sqrt{s^2}`,
    meaning:pair('Here s² is sample variance, with denominator n − 1. Describing an entire finite population uses n instead. R var() and sd() use n − 1; NumPy needs ddof=1 to match.','這裏 s² 是樣本方差，分母為 n − 1。描述整個有限總體時可用 n。R 的 var()、sd() 用 n − 1；NumPy 要設 ddof=1 才一致。'),
    steps:[pair('Move the last data value far to the right.','把最後一個數據值移到很右的位置。'),pair('Compare the movement of the mean and median markers.','比較平均數和中位數標記移動了多少。'),pair('Paste your own numbers, separated by commas or spaces.','貼上自己的數字，以逗號或空格分隔。')],
    example:pair('For 2, 4, 4, 6, 9, the mean is 5, median 4, sample variance 7, and sample SD √7 ≈ 2.65. Changing 9 to 30 pulls the mean strongly upward.','2、4、4、6、9 的平均數為 5，中位數為 4，樣本方差為 7，樣本標準差為 √7 ≈ 2.65。把 9 改成 30 會大幅拉高平均數。'),
    trap:pair('A small spread does not prove your sample represents the population. Sampling design matters.','分散程度小，不代表樣本能代表總體；抽樣方法也很重要。'),
    quiz:{q:pair('Which usually changes less when one value becomes extremely large?','一個數值變得極大時，哪項通常變化較小？'),options:['Mean / 平均數','Median / 中位數','Both always equally / 永遠一樣'],answer:1,why:pair('The median depends on order, not the magnitude of an extreme value.','中位數取決於排序位置，不直接取決於極端值的大小。')},ref:'Bridge lesson; Wasserman §3.3, printed p. 50',
    py:'import numpy as np\nimport matplotlib.pyplot as plt\nx = np.array([2, 4, 4, 6, 9])\nprint(x.mean(), np.median(x), x.std(ddof=1))\nplt.hist(x, bins=5, edgecolor="white")\nplt.show()',
    r:'x <- c(2, 4, 4, 6, 9)\nprint(c(mean=mean(x), median=median(x), sd=sd(x)))\nhist(x, breaks=5, col="seagreen3", main="Our data")'
  },
  {
    id:'probability',group:'Statistics',title:'Count uncertain outcomes',zh:'機率與二項分布',time:12,lab:'probability',
    subtitle:pair('From one trial to a distribution of many trials.','從一次試驗，走到多次試驗的分布。'),
    idea:pair('A Bernoulli trial returns 1 for success and 0 for failure. If n trials are independent with the same success probability p, the number of successes follows a binomial distribution. Its bars show probability, not the result of a particular experiment.','伯努利試驗以 1 表示成功、0 表示失敗。若 n 次試驗獨立且成功機率同為 p，成功次數服從二項分布。圖中各柱表示機率，不是某一次實驗的結果。'),
    formula:String.raw`P(X=k)=\binom nk p^k(1-p)^{n-k},\qquad E[X]=np,\quad \operatorname{Var}(X)=np(1-p)`,
    meaning:pair('The binomial coefficient counts the different arrangements of k successes. Expected value is a long-run average; it does not have to be an outcome you can observe.','二項係數計算 k 次成功的不同排列方式。期望值是長期平均，不一定是可能觀察到的單一結果。'),
    steps:[pair('Try n = 10 and p = 0.5, then make success rare.','試 n = 10、p = 0.5，再把成功機率調低。'),pair('Change the highlighted k to read P(X = k).','改變標示的 k，讀出 P(X = k)。'),pair('Run simulated trials and compare frequencies with the theoretical bars.','執行模擬，比較實際頻率與理論機率柱。')],
    example:pair('For three independent fair coin tosses, P(exactly two heads) = 3 × (1/2)³ = 3/8. The expected number of heads is 1.5.','獨立擲三次公平硬幣，恰好兩次正面的機率為 3 × (1/2)³ = 3/8；正面次數的期望值為 1.5。'),
    trap:pair('Without independence or a common p, the binomial model can fail. Repeated trials do not force the observed count to equal np.','如果試驗不獨立，或 p 不固定，二項模型可能不適用。重複試驗也不會保證每次結果都等於 np。'),
    quiz:{q:pair('For Binomial(10, 0.3), what is E[X]?','Binomial(10, 0.3) 的 E[X] 是多少？'),options:['0.3','3','7'],answer:1,why:pair('E[X] = np = 10 × 0.3 = 3.','E[X] = np = 10 × 0.3 = 3。')},ref:'Wasserman §1.5 and §2.3, printed pp. 8, 25',
    py:'from scipy.stats import binom\nimport matplotlib.pyplot as plt\nk = range(11)\nprint(binom.pmf(3, n=10, p=0.3))\nplt.bar(k, binom.pmf(k, 10, 0.3))\nplt.xlabel("Successes"); plt.ylabel("Probability")\nplt.show()',
    r:'k <- 0:10\nprint(dbinom(3, size=10, prob=0.3))\nbarplot(dbinom(k, 10, 0.3), names.arg=k,\n        xlab="Successes", ylab="Probability")'
  },
  {
    id:'normal',group:'Statistics',title:'Read the bell curve',zh:'常態分布的面積',time:12,lab:'normal',
    subtitle:pair('Probability is area, not height.','機率是面積，不是高度。'),
    idea:pair('A continuous distribution has a density curve. Probability comes from the area between two values. The normal distribution is centered at μ; σ controls its spread. Standardizing turns a value into a number of standard deviations from the mean.','連續分布用密度曲線表示。兩個數值之間的面積就是機率。常態分布以 μ 為中心，σ 控制分散程度；標準化把數值轉成離平均數多少個標準差。'),
    formula:String.raw`f(x)=\frac{1}{\sigma\sqrt{2\pi}}e^{-\frac12((x-\mu)/\sigma)^2},\qquad z=\frac{x-\mu}{\sigma},\quad P(a\le X\le b)=F(b)-F(a)`,
    meaning:pair('The total area is 1. For a continuous variable, P(X = exactly x) = 0 even when the density is high. The CDF F(x) gives the area to the left of x.','總面積為 1。連續變量剛好等於某個數值的機率為 0，即使該處密度很高。累積分布函數 F(x) 表示 x 左邊的面積。'),
    steps:[pair('Widen σ and watch the peak become lower.','增大 σ，觀察峰值降低。'),pair('Move the lower and upper bounds to change the shaded area.','移動上下界，改變陰影面積。'),pair('Use μ − σ to μ + σ and check the familiar 68% region.','設定 μ − σ 至 μ + σ，看看熟悉的約 68% 區域。')],
    example:pair('If X ~ Normal(100, 15²), then x = 130 has z = 2. About 95.45% lies between 70 and 130, the interval μ ± 2σ.','若 X ~ Normal(100, 15²)，x = 130 的 z = 2。約 95.45% 機率落在 70 至 130，即 μ ± 2σ。'),
    trap:pair('Data are not automatically normal. A bell-shaped model should be checked against the data and context.','數據不會自動服從常態分布，應用模型前要檢查數據及背景。'),
    quiz:{q:pair('For a continuous normal variable, P(X = μ) is…','連續常態變量的 P(X = μ) 是⋯'),options:['0','0.5','1'],answer:0,why:pair('A single point has zero width and therefore zero area.','單一點寬度為零，面積也為零。')},ref:'Wasserman §2.4, printed p. 27',
    py:'from scipy.stats import norm\nmu, sigma = 100, 15\np = norm.cdf(130, mu, sigma) - norm.cdf(70, mu, sigma)\nprint(p)                   # about 0.9545',
    r:'mu <- 100; sigma <- 15\np <- pnorm(130, mu, sigma) - pnorm(70, mu, sigma)\nprint(p)                   # about 0.9545'
  },
  {
    id:'sampling',group:'Statistics',title:'Samples vary. Patterns remain.',zh:'抽樣分布與信賴區間',time:15,lab:'sampling',
    subtitle:pair('Watch the central limit theorem take shape.','親眼看見中央極限定理。'),
    idea:pair('A sample mean changes from sample to sample. Its standard error is σ/√n for independent identically distributed observations with finite variance. The central limit theorem says the distribution of the standardized mean approaches normal as n grows, even when the original population is skewed.','樣本平均數會隨抽樣而改變。獨立同分布且方差有限時，標準誤為 σ/√n。中央極限定理指出，n 增大時，標準化樣本平均數的分布趨近常態，即使原總體偏斜。'),
    formula:String.raw`\operatorname{SE}(\bar X)=\frac{\sigma}{\sqrt n},\qquad \bar X\pm1.96\frac{\sigma}{\sqrt n}`,
    meaning:pair('The displayed 95% intervals use known population σ and a normal approximation. Coverage is exact for a normal population and approximate for an exponential one. With unknown σ, a t interval is usual for normal data.','圖中的 95% 區間使用已知總體 σ 與常態近似。常態總體的覆蓋率是精確的；指數總體則是近似的。若 σ 未知，常態數據一般使用 t 區間。'),
    steps:[pair('Choose a skewed exponential population and n = 2.','選偏斜的指數總體，設定 n = 2。'),pair('Generate 500 samples, then repeat with n = 40.','產生 500 個樣本，再用 n = 40 重試。'),pair('Inspect the intervals: some miss the true mean, even with good data.','觀察區間：即使數據良好，也有一些未覆蓋真實平均數。')],
    example:pair('With σ = 2, n = 4 gives SE = 1; n = 100 gives SE = 0.2. A 95% method covers the fixed true mean in about 95% of repeated samples, under its assumptions.','σ = 2 時，n = 4 得 SE = 1；n = 100 得 SE = 0.2。符合假設時，95% 方法在重複抽樣中約有 95% 區間覆蓋固定的真實平均數。'),
    trap:pair('A frequentist 95% interval is not a statement that the fixed parameter has a 95% probability of being inside this particular realized interval.','頻率學派的 95% 區間，不表示固定參數有 95% 機率落在這次已算出的區間內。'),
    quiz:{q:pair('To halve the standard error, multiply n by…','要把標準誤減半，n 要乘以⋯'),options:['2','4','8'],answer:1,why:pair('SE scales as 1/√n. Four times the sample size halves it.','SE 按 1/√n 改變，樣本量增至四倍會使它減半。')},ref:'Wasserman §5.4 and §6.3.2, printed pp. 77, 92',
    py:'import numpy as np\nimport matplotlib.pyplot as plt\nrng = np.random.default_rng(42)\nmeans = rng.exponential(1, size=(500, 40)).mean(axis=1)\nprint(means.std(ddof=1), 1/np.sqrt(40))\nplt.hist(means, bins=25); plt.show()',
    r:'set.seed(42)\nmeans <- replicate(500, mean(rexp(40, rate=1)))\nprint(c(observed=sd(means), theoretical=1/sqrt(40)))\nhist(means, breaks=25, main="Sample means")'
  },
  {
    id:'regression',group:'Statistics',title:'The best line is a projection',zh:'回歸與最小二乘法',time:15,lab:'regression',
    subtitle:pair('Where linear algebra and statistics meet.','線性代數與統計相遇之處。'),
    idea:pair('Fit a line by choosing an intercept and slope that minimize the sum of squared vertical residuals. The columns of the design matrix are a column of ones and the x-values. The fitted y-vector is the projection of the observed y-vector onto their span.','選擇截距和斜率，使垂直殘差的平方和最小。設計矩陣的直列是一列 1 和一列 x 值。擬合的 y 向量就是把觀察到的 y 向量投影到這些直列張成的空間。'),
    formula:String.raw`\hat y_i=\beta_0+\beta_1x_i,\qquad \hat\beta=\arg\min_\beta\|X\beta-\mathbf y\|^2,\quad X=\begin{bmatrix}1&x_1\\\vdots&\vdots\\1&x_n\end{bmatrix}`,
    meaning:pair('Residuals are observed minus fitted values. With full column rank, the normal equations are XᵀXβ̂ = Xᵀy. Numerical libraries normally use more stable factorizations instead of explicitly inverting XᵀX.','殘差是觀察值減擬合值。直列滿秩時，正規方程為 XᵀXβ̂ = Xᵀy。數值函式通常用更穩定的分解方法，而不是直接求 XᵀX 的逆。'),
    steps:[pair('Drag a data point and watch the best-fit line update.','拖動數據點，觀察最佳擬合直線更新。'),pair('Compare the residual lines and the sum of squares.','比較殘差線段與平方和。'),pair('Move one point far away. Least squares is sensitive to outliers.','把一個點移遠，觀察最小二乘法對離群值的敏感程度。')],
    example:pair('For x = [1, 2, 3] and y = [2, 3, 5], the best line is ŷ = 1/3 + 1.5x. Its residuals are [1/6, −1/3, 1/6], and their sum is zero because the model includes an intercept.','x = [1, 2, 3]、y = [2, 3, 5] 時，最佳直線是 ŷ = 1/3 + 1.5x。殘差為 [1/6, −1/3, 1/6]；因模型包含截距，殘差總和為零。'),
    trap:pair('A good fit does not establish causation. R² measures fit on these data, not whether your assumptions or predictions are valid.','擬合良好不代表因果關係。R² 量度這批數據的擬合程度，不證明假設或預測有效。'),
    quiz:{q:pair('Which quantity does ordinary least squares minimize?','普通最小二乘法最小化哪一項？'),options:['Sum of residuals / 殘差總和','Sum of squared residuals / 殘差平方和','Number of points / 點的數目'],answer:1,why:pair('Squaring prevents positive and negative errors from canceling, and penalizes large errors.','平方避免正負誤差互相抵消，並加重較大誤差的影響。')},ref:'Strang §4.3, printed p. 219; Wasserman §13.1–13.2, printed pp. 209–212',
    py:'import numpy as np\nx, y = np.array([1., 2., 3.]), np.array([2., 3., 5.])\nX = np.column_stack([np.ones_like(x), x])\nbeta, *_ = np.linalg.lstsq(X, y, rcond=None)\nprint(beta)                # [0.33333333 1.5]\nprint(y - X @ beta)',
    r:'x <- c(1, 2, 3); y <- c(2, 3, 5)\nfit <- lm(y ~ x)\nprint(coef(fit))           # intercept 1/3; slope 1.5\nprint(residuals(fit))\nplot(x, y); abline(fit, col="seagreen4")'
  },
  {
    id:'bootstrap',group:'Statistics',title:'Let your sample teach you',zh:'自助法：從樣本再抽樣',time:12,lab:'bootstrap',
    subtitle:pair('Estimate uncertainty by resampling with replacement.','以有放回再抽樣估計不確定性。'),
    idea:pair('Treat the observed sample as a small stand-in for the population. Draw new samples of the same size with replacement, calculate a statistic each time, and examine its distribution. This bootstrap distribution helps estimate the sampling uncertainty of that statistic.','把觀察樣本當作總體的小型替身。有放回地抽取相同大小的新樣本，每次計算統計量，觀察其分布。這個自助分布幫助估計統計量的抽樣不確定性。'),
    formula:String.raw`x_1^*,\ldots,x_n^*\sim\widehat F,\qquad \mathrm{CI}_{\mathrm{percentile}}=[q_{0.025}(\bar x^*),\ q_{0.975}(\bar x^*)]`,
    meaning:pair('The percentile interval uses the middle 95% of bootstrap means. It is an approximate method; small samples, biased estimators, and unusual distributions can give poor coverage.','百分位區間取自助平均數分布中間的 95%，是一種近似方法。小樣本、有偏估計量或特殊分布可能導致覆蓋率欠佳。'),
    steps:[pair('Enter a sample and generate 1,000 bootstrap means.','輸入樣本，產生 1,000 個自助平均數。'),pair('Inspect one resample: repeated values are expected.','檢視一個再抽樣：出現重複值是正常的。'),pair('Change an outlier and regenerate to see how the interval changes.','改變離群值後重新模擬，觀察區間變化。')],
    example:pair('From [2, 4, 4, 6, 9], one possible resample is [4, 9, 4, 2, 4], with mean 4.6. Repeating this many times approximates the distribution of sample means under the empirical population.','由 [2, 4, 4, 6, 9] 可再抽出 [4, 9, 4, 2, 4]，平均數為 4.6。大量重複便近似以經驗總體抽樣的平均數分布。'),
    trap:pair('Resampling cannot fix a biased original sample. More bootstrap repetitions reduce simulation noise, not missing information.','再抽樣不能修正原樣本的偏差。增加自助次數只能減少模擬雜訊，不能補回缺失資訊。'),
    quiz:{q:pair('Why sample with replacement?','為甚麼要有放回抽樣？'),options:['To get different samples / 得到不同樣本','To guarantee 95% coverage / 保證 95% 覆蓋率','To remove all outliers / 移除所有離群值'],answer:0,why:pair('Without replacement, a full-size resample is just a permutation; its mean would never change.','若無放回抽取完整樣本，只會改變排序，平均數永遠相同。')},ref:'Wasserman §8.1–8.3, printed pp. 108–110',
    py:'import numpy as np\nrng = np.random.default_rng(42)\nx = np.array([2, 4, 4, 6, 9])\nmeans = rng.choice(x, size=(1000, len(x)), replace=True).mean(axis=1)\nprint(np.quantile(means, [0.025, 0.975]))',
    r:'set.seed(42)\nx <- c(2, 4, 4, 6, 9)\nmeans <- replicate(1000, mean(sample(x, length(x), replace=TRUE)))\nprint(quantile(means, c(0.025, 0.975)))'
  }
];
export const byId = id => lessons.find(l=>l.id===id);
