import { label, renderMath } from './ui.js';
export function renderNotes(root, footer) {
  root.innerHTML=String.raw`<div class="breadcrumb">Keep the useful things close / 把有用的知識放在手邊</div>
  <h1>${label('Your mathematical field notes.','你的數學學習筆記。')}</h1>
  <p class="subtitle">${label('A reading route, a small toolkit, and a rhythm that fits a busy week.','閱讀路線、小型工具箱，以及適合忙碌生活的學習節奏。')}</p>
  <section id="rhythm" style="margin-top:35px"><h2>${label('Ten minutes is enough to begin.','十分鐘，已足夠開始。')}</h2>
  <p class="prose">${label('With your Core + M1 background, start at vectors; use the probability lessons as a visual refresher. Aim for one lesson per day, and repeat the experiment without looking at the explanation the next day. There is no deadline.','以你的 Core + M1 基礎，可直接由向量開始；機率課可當作視覺複習。每天一課，翌日試試不看說明重做實驗。這裏沒有截止日期。')}</p>
  <div class="learning-plan"><article><span class="eyebrow">Days 1–4 / 第 1–4 天</span><h3>Arrows → transformations</h3><p>${label('Vectors, span, dot products, matrices. Get comfortable with the pictures.','向量、張成空間、內積、矩陣。先熟悉圖像。')}</p></article><article><span class="eyebrow">Days 5–8 / 第 5–8 天</span><h3>Structure → solutions</h3><p>${label('Composition, systems, determinants, eigenvectors. Connect the pictures to equations.','合成、方程、行列式、特徵向量。把圖像連到方程。')}</p></article><article><span class="eyebrow">Days 9–14 / 第 9–14 天</span><h3>Data → uncertainty</h3><p>${label('Summaries, probability, normal curves, sampling, regression, bootstrap.','數據摘要、機率、常態曲線、抽樣、回歸、自助法。')}</p></article></div>
  <div class="callout">${label('For each lesson: 2 minutes to read, 5 to experiment, 3 to explain it back to yourself. If you have more time, run the code and read the suggested book section.','每課可分成：2 分鐘閱讀、5 分鐘實驗、3 分鐘用自己的話解釋。有餘裕再執行程式、閱讀書中章節。')}</div></section>
  <section id="books"><h2>${label('Two books. A gentler route.','兩本參考書，一條易入門的路。')}</h2>
  <div class="notes-grid"><article class="note-card"><span class="book-tag">01 · LINEAR ALGEBRA</span><h2>Introduction to<br>Linear Algebra</h2><p>Gilbert Strang · Fourth edition / 第四版</p><p>${label('Read the matching section after the visual lesson. The geometric route can make the formal definitions feel less abstract.','先完成視覺課程，再讀相應章節。幾何路線能令正式定義不再那麼抽象。')}</p><ol><li>§1.1–1.3 · Vectors, dot products, matrices / 向量、內積、矩陣</li><li>§2.1–2.5 · Equations, multiplication, inverses / 方程、乘法、逆矩陣</li><li>§3.5 · Independence, basis, dimension / 獨立、基底、維度</li><li>§4.2–4.3 · Projection & least squares / 投影、最小二乘</li><li>§5.1, §6.1 · Determinants & eigenvectors / 行列式、特徵向量</li></ol><a class="btn secondary small" href="ref/Intro_To_Linear_Algebra.pdf" target="_blank" rel="noopener">Open your PDF / 開啟 PDF ↗</a></article>
  <article class="note-card"><span class="book-tag">02 · STATISTICS</span><h2>All of<br>Statistics</h2><p>Larry Wasserman</p><p>${label('The preface assumes calculus and a little linear algebra. Use these lessons as a bridge, then read selected sections instead of rushing through the full text.','序言預設讀者懂微積分和少量線性代數。可先用這些課程搭橋，再讀選定章節。')}</p><ol><li>Ch. 1–2 · Probability & random variables / 機率、隨機變量</li><li>§3.1–3.3 · Expectation & variance / 期望值、方差</li><li>§5.3–5.4 · LLN & CLT / 大數法則、中央極限定理</li><li>§6.3.2, §8.1–8.3 · Intervals & bootstrap / 區間、自助法</li><li>§13.1–13.2 · Linear regression / 線性回歸</li></ol><a class="btn secondary small" href="ref/all-of-statistics.pdf" target="_blank" rel="noopener">Open your PDF / 開啟 PDF ↗</a></article></div>
  <p class="source-note">Original explanations and exercises accompany the supplied books. Chapter mappings were checked against the local tables of contents. / 說明與練習為原創；章節對照已按本地書籍目錄核對。</p></section>
  <section id="code" style="margin-top:40px"><h2>${label('Meet Python and R.','認識 Python 與 R。')}</h2>
  <p class="prose">${label('The browser experiments run immediately. The code examples run separately in Python or R; the page does not send your data to a server. Each lesson includes a small runnable example and a download button.','瀏覽器實驗可即時運作。程式示例則在 Python 或 R 另外執行，頁面不會把你的數據傳到伺服器。每課都有可執行示例及下載按鈕。')}</p>
  <div class="notes-grid"><article class="note-card"><h3>Python · arrays and data / 陣列與數據</h3><p>${label('NumPy gives you arrays and linear algebra. SciPy adds probability distributions. Matplotlib draws plots. pandas organizes tables into DataFrames.','NumPy 處理陣列和線性代數；SciPy 提供機率分布；Matplotlib 繪圖；pandas 以 DataFrame 整理資料表。')}</p><pre class="setup-code">python -m pip install numpy scipy matplotlib pandas</pre><p>${label('Use a .py file or a Jupyter notebook. A cell executes when you run it; variables remain available in later cells.','可以使用 .py 檔或 Jupyter 筆記本。執行一格後，變數可在之後的格中使用。')}</p><a href="examples/start_here.py" download class="btn secondary small">↓ Python starter / 入門檔</a> <a href="examples/linear_algebra_statistics.ipynb" download class="btn secondary small">↓ Notebook</a><p style="margin:15px 0 0;font-size:11px"><a href="https://numpy.org/doc/stable/user/absolute_beginners.html" target="_blank" rel="noopener">NumPy introduction ↗</a> · <a href="https://pandas.pydata.org/docs/getting_started/intro_tutorials/" target="_blank" rel="noopener">pandas ↗</a></p></article>
  <article class="note-card"><h3>R · a language for statistics / 統計語言</h3><p>${label('Base R already includes vectors, matrices, distributions, plots, and linear models. Start with c() for a vector, data.frame() for a table, and lm() for a fitted line.','R 本身已包含向量、矩陣、分布、繪圖、線性模型。可先學 c() 建向量、data.frame() 建表格、lm() 擬合直線。')}</p><pre class="setup-code">x &lt;- c(1, 2, 3)
y &lt;- c(2, 3, 5)
fit &lt;- lm(y ~ x)
summary(fit)</pre><p>${label('Run code in the R console or an .R script. R indexes from 1; Python indexes from 0. R fills matrices column by column unless byrow=TRUE.','可在 R console 或 .R 檔執行。R 索引由 1 開始，Python 由 0 開始。R 預設逐直列填矩陣，除非設 byrow=TRUE。')}</p><a href="examples/start_here.R" download class="btn secondary small">↓ R starter / 入門檔</a><p style="margin:15px 0 0;font-size:11px"><a href="https://stat.ethz.ch/CRAN/doc/manuals/R-intro.html" target="_blank" rel="noopener">Official R introduction / 官方入門 ↗</a></p></article></div></section>
  <section style="margin-top:38px"><h2>${label('Keep this translation table.','留起這張對照表。')}</h2><div class="table-wrap"><table class="reference-table"><thead><tr><th>Idea / 概念</th><th>Math / 數學</th><th>Python</th><th>R</th></tr></thead><tbody><tr><td>Vector / 向量</td><td>\(\mathbf v\)</td><td><code>np.array([1, 2])</code></td><td><code>c(1, 2)</code></td></tr><tr><td>Matrix product / 矩陣乘法</td><td>\(AB\)</td><td><code>A @ B</code></td><td><code>A %*% B</code></td></tr><tr><td>Transpose / 轉置</td><td>\(A^T\)</td><td><code>A.T</code></td><td><code>t(A)</code></td></tr><tr><td>Solve / 求解</td><td>\(A\mathbf x=\mathbf b\)</td><td><code>np.linalg.solve(A, b)</code></td><td><code>solve(A, b)</code></td></tr><tr><td>Sample SD / 樣本標準差</td><td>\(s\)</td><td><code>np.std(x, ddof=1)</code></td><td><code>sd(x)</code></td></tr><tr><td>Normal CDF / 常態 CDF</td><td>\(P(X\le x)\)</td><td><code>scipy.stats.norm.cdf(x)</code></td><td><code>pnorm(x)</code></td></tr><tr><td>Least squares / 最小二乘</td><td>\(\arg\min\|X\beta-y\|^2\)</td><td><code>np.linalg.lstsq(X, y, rcond=None)</code></td><td><code>lm(y ~ x)</code></td></tr></tbody></table></div></section>
  <section style="margin-top:38px"><h2>${label('After the basics.','基礎之後。')}</h2><p class="prose">${label('Return to the reference books for the four fundamental subspaces, Gram–Schmidt, symmetric matrices, SVD and PCA, conditional probability and Bayes, hypothesis testing, and multiple regression. These are suggested next topics, beyond the 14 lessons in this site.','可回到參考書學習四個基本子空間、Gram–Schmidt、對稱矩陣、SVD 與 PCA、條件機率與貝氏定理、假設檢定，以及多元回歸。這些是網站 14 課以外的建議進階題目。')}</p></section>
  <section style="margin-top:35px"><h3>Your progress / 你的進度</h3><p class="prose">${label('Understood lessons and quiz successes stay in this browser. They are not an exam score. Reset only when you want a fresh start.','已掌握課程及答對紀錄只儲存在這個瀏覽器，不是考試成績。想重新開始才重設。')}</p><button class="btn secondary small" id="clear-progress">Reset learning progress / 重設學習進度</button><span id="reset-message" class="save-status" role="status"></span></section>${footer}`;
  renderMath(root);
}
